#
version: 2
jobs:
  wasm-libicu:
    docker: 
      - image: trzeci/emscripten

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-wasm-libicu-{{ checksum "wasm-libicu/branch.sh" }}

      - run:
          command: |
            if [ ! -d wasm-libicu/dist ]
            then
            #  source emsdk/emsdk_env.sh
              cd wasm-libicu
              npm run build
              npm pack
            fi

      - save_cache:
          paths:
            - wasm-libicu/dist
          key: v1-wasm-libicu-{{ checksum "wasm-libicu/branch.sh" }}


  wasm-protobuf:
    docker: 
      - image: trzeci/emscripten

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-wasm-protobuf-{{ checksum "wasm-protobuf/branch.sh" }}

      - run:
          command: |
            if [ ! -d wasm-protobuf/dist ]
            then
              apt update -y
              apt install -y autoconf libtool
              cd wasm-protobuf
              npm run build
              npm pack
            fi

      - save_cache:
          paths:
            - wasm-protobuf/dist
          key: v1-wasm-protobuf-{{ checksum "wasm-protobuf/branch.sh" }}

  wasm-intl-native-protobuf:
    docker: 
      - image: trzeci/emscripten

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-wasm-intl-native-protobuf-{{ checksum "wasm-protobuf/branch.sh" }}

      - run:
          command: |
            if [ ! -d wasm-intl/generated/protobuf/dist ]
            then
              apt update -y
              apt install -y autoconf libtool
              cd wasm-intl
              bash -x native-protobuf.sh
            fi

      - save_cache:
          paths:
            - generated/protobuf/dist
          key: v1-wasm-intl-native-protobuf-{{ checksum "wasm-protobuf/branch.sh" }}


  wasm-intl:
    docker: 
      - image: trzeci/emscripten

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-wasm-libicu-{{ checksum "wasm-libicu/branch.sh" }}

      - restore_cache:
          keys:
            - v1-wasm-protobuf-{{ checksum "wasm-protobuf/branch.sh" }}

      - run:
          command: |
            # source emsdk/emsdk_env.sh
            cd wasm-intl
            npm install
            npm run build
            npm run test
            npm pack

workflows:
  version: 2
  build_and_test:
    jobs:
      - wasm-libicu
      - wasm-protobuf
      - wasm-intl-native-protobuf
      - wasm-intl:
          requires:
            - wasm-intl-native-protobuf
            - wasm-libicu
            - wasm-protobuf


