#
version: 2
jobs:
  libicu:
    docker: 
      - image: circleci/node:dubnium
    steps:
      - checkout

      - restore_cache:
          keys:
            - wasm-libicu-{{ checksum "wasm-libicu/branch.sh" }}

      - run: cd wasm-libicu && npm run build && npm pack

      - save_cache:
          paths:
            - wasm-libicu
          key: wasm-libicu-{{ checksum "wasm-libicu/branch.sh" }}

   wasmintl:
    docker: 
      - image: circleci/node:dubnium
    steps:
      - checkout

      - restore_cache:
          keys:
            - wasm-intl-{{ checksum "wasm-intl/package.json" }}

      - run: cd wasm-intl && npm install && npm run build && npm run test && npm pack

      - save_cache:
          paths:
            - wasm-intl
          key: wasm-intl-{{ checksum "wasm-intl/package.json" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - libicu
      - wasmintl

